repos:
  - repo: local
    hooks:
      #- id: flake8
      #  name: flake8
      #  entry: poetry run flake8 backend
      #  types: [ python ]
      #  language: system

      - id: black
        name: Black
        entry: poetry run black .
        types: [ python ]
        language: system

      